version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for updates to GitHub Actions every month
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
